### ISSUE TITLE
What features are supported? License file?

### ISSUE THREAD

**Issue by mohamed82008** [SwanLab/Swan#101]
Hi! 

I am compiling a list of open source topology optimization software and the features they support. Swan's documentation doesn't seem to explain the supported features and there is a lack of examples. From a quick look at the code, I see that SIMP is implemented for volume constrained compliance minimization with unstructured ground meshes. I also see some homgenization and level set methods but it is unclear what problem types they support. May you give me a summary of the features available in Swan? Thank you! Also, I can't find a license file, is this intentional?

**Comment by Trujillo94** [comment]
Hello,

You are right. At the moment the documentation available is incomplete, we
will notify you in the following weeks once we update the information and
license.

In short, SwanLab could be described as a Topology Optimization Laboratory,
meaning it is not intended for HPC of large cases, but to provide an
extremely agile tool to develop and test new strategies and features
(optimizers, material interpolation schemes, design variables, etc.).

That is why the code is programmed in Matlab (priorizing developing time
rather than running time) and Object-Oriented with the best practices of
Clean Code (to keep the different modules decoupled aiming to add new
features).

A first release will be launched on September. At the moment it is
supported:

   - Design variables: density & level-set (multi-variable is in
   development).
   - Scales: Micro and Macro.
   - Optimizers: (the list will grow very fast at some point)
      - Density: Projected gradient, MMA and IPOPT.
      - Level-set: SLERP, projected SLERP and Hamilton-Jacobi (the latter
      is for Shape Optimization).
   - Problem types:


   - Min. Compliance s.t. Volume
      - Min. Compliance & Volume s.t. Perimeter.
      - Gripping.
      - Homogenization.
      - [In development] Problem types with stress.
   - Material interpolation: SIMP, SIMP-ALL.
   - Accurate integration of level-set through Unfitted Mesh.
   - Filters: P1 and PDE.

It is possible that I missed something, as I said, we'll notify you as soon
we update the documentation.

By the way, your work is very interesting, we are looking forward to see
the data that you compile.

Kind regards,

Oriol.

Missatge de Mohamed Tarek <notifications@github.com> del dia dt., 2 d’abr.
2019 a les 16:42:
